# Generated by Django 5.2 on 2025-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=120)),
                ('prodcuctDescription', models.TextField(blank=True, null=True)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isAvailable', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
