# Generated by Django 5.2 on 2025-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maxQuantityPerOrder',
            field=models.IntegerField(default=5, help_text='Maximum quantity allowed per order for this product.'),
        ),
    ]
